image: python:3.9

stages:
  - test

test:
  stage: test

  before_script:
    - echo "Install environment"
    - pip3 install -r requirements.txt

  script:
    - echo "Run all tests"
    - py.test --alluredir=results

    # Отправка отчетов о тестах в группу
    - echo "Send report to chat"
    - allureserve results

  artifacts:
    paths:
      - /results
    expire_in: 1 month